const config = {
	MODE: 'development', // localhost development production
	PORT: {
		400: '4020',
		3002: '53002'
	},
	SERVE_URL: {
		localhost: 'http://localhost:',
		development: 'https://mp-dev.guzzu.cn',
		production: 'https://mp.guzzu.cn'
	},
	API_PREFIX: {
		400: '/api/2/',
		3002: '/v3/frontapi/'
	},
	SESSION_KEY: {
		400: 'x-guzzu-sessionid',
		3002: 'x-guzzu-access-token'
	},
	SESSION_EXPIRE_SECONDS: 600,
	'INDEX_SLUG': 'guzzu-msite-index',
	'shoppingMallId': '5adedc43de3c90022eb25d3b',
	SESSION_REQUIRE: [
		'Auth.getCurrentSession',
		'Auth.removeSession',
		'Auth.bindMobilePhone',
		'StoreCart.get',
		'StoreCart.addItem',
		'StoreCart.updateItem',
		'StoreCart.removeItem',
		'StoreCart.preview',
		'StoreCart.clear',
		'StoreCart.getAll',
		'Discount.findAvailable',
		'Discount.getByPromoCode',
		'Discount.get',
		'ProductDiscount.find',
		'UserDiscount.get',
		'UserDiscount.find',
		'UserDiscount.findByStore',
		'UserDiscount.create',
		'UserAddress.getLastUsed',
		'UserAddress.find',
		'UserAddress.get',
		'UserAddress.create',
		'UserAddress.update',
		'UserAddress.remove',
		'Order.preview',
		'Order.create',
		'Order.createForMembership',
		'Order.createForTicket',
		'Order.previewForTicket',
		'Order.get',
		'Order.find',
		'Order.customerRequestRefund',
		'Order.confirmReceipt',
		'Order.createStoreRating',
		'Order.findAllByStatus',
		'ShareCampaignInstance.getByOrder',
		'ShareCampaignInstance.getCoupon',
		'StoreConversation.hasUnread',
		'StoreConversation.find',
		'StoreConversation.clearCustomerUnread',
		'StoreConversationItem.find',
		'AreaShipping.get',
		'PickUpPlace.find',
		'ProductReview.getByOrderItem',
		'ProductReview.create',
		'ProductReview.updatePrimaryReview',
		'ProductReview.createAdditionalReview',
		'ProductReviewLike.update',
		'UserMembership.get',
		'UserMembership.find',
		'UserMembership.findByStore',
		'Membership.findAvailable',
		'UserTicket.get',
		'UserTicket.getByOrder',
		'UserTicket.find',
	],
};

module.exports = config;
